#!/bin/bash

jalpar_secret_verify() {
  if [ "$#" -ne 3 ]; then
    echo "Script requires:"
    echo "1. Container Directory"
    echo "2. Container Name"
    echo "3. Redundancy"
    exit 1
  fi
  CONTAINER_DIRECTORY=$1
  CONTAINER_NAME=$2
  REDUNDANCY=$3

  DISK_PREFIX=$CONTAINER_DIRECTORY/$CONTAINER_NAME

  declare -a HASH_ARRAY=()

  for((i=0; i < $REDUNDANCY; ++i));
  do
    HASH=($(sha512sum $DISK_PREFIX/disk.$i | xargs | cut -d" " -f1))
    HASH_ARRAY+=($HASH)
  done

  for((i=0; i < $REDUNDANCY; ++i));
  do
    for((j=0; j < $REDUNDANCY; ++j));
    do
      if [[ ${HASH_ARRAY[$i]} != ${HASH_ARRAY[$j]} ]]; then
        echo "Copies do not match."
        for((k=0; k < $REDUNDANCY; ++k));
        do
          echo "hash[$k] = ${HASH_ARRAY[$k]}"
        done
        return 1
      fi
    done
  done

  return 0
}
